@authToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc5Mzk4OTk5LCJleHAiOjE3Nzk0Mjc3OTl9.peeeLaEm47ETa7euk4qta3kZvknn9wTtGsrMgf2BPaU
//admin @authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc5Mzk4OTk5LCJleHAiOjE3Nzk0Mjc3OTl9.peeeLaEm47ETa7euk4qta3kZvknn9wTtGsrMgf2BPaU
//user @authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3Nzk0MDA3NzYsImV4cCI6MTc3OTQyOTU3Nn0.a-qXrMtLZD8QjO6RLqMb3cgbsL7LHX2iaIGGtvWR0nA

GET http://localhost:3000/api/tasks

###

POST http://localhost:3000/api/tasks/1
Content-Type: application/json 
Authorization: Baerer {{authToken}}

{
    "taskTitle": "teste3",
    "content": "rua",
    "taskStatus": "open"
}

###

PATCH http://localhost:3000/api/tasks/1
Content-Type: application/json
Authorization: Baerer {{authToken}}

{
    "taskTitle": "teste atualizado",
    "content": "funcionando2"
}

###

DELETE http://localhost:3000/api/tasks/3
Authorization: Baerer {{authToken}}
###

PATCH  http://localhost:3000/api/tasks/2/changeStatus
Authorization: Baerer {{authToken}}