@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NzkyMzUzMjUsImV4cCI6MTc3OTI2NDEyNX0.KR19uu08OvsazRv4KuG219Ys8AGfR4VGQvFjQIt_gA0


POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "teste@test.com",
  "password": "123456"
}

###

GET http://localhost:3000/api/users/
###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "test1",
    "lastName": "test",
    "email": "teste@test.com",
    "password": "123456"
}

###
DELETE http://localhost:3000/api/users/1
###

PATCH http://localhost:3000/api/users/2
Content-Type: application/json

{
    "name": "test2",
    "lastName": "test2",
    "email": "teste2@test.com"
}

###

PATCH http://localhost:3000/api/users/1/active