@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc5MzIxOTAyLCJleHAiOjE3NzkzNTA3MDJ9.8FAa7F-UgvZB-9PmL_xV3O6WVgGMD6m2FcnOXiPlsQE


POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "teste2@test.com",
  "password": "123456"
}

###

GET http://localhost:3000/api/users/
###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "test2",
    "lastName": "test2",
    "email": "teste2@test.com",
    "password": "123456",
    "role": "user"
}

###
DELETE http://localhost:3000/api/users/
###

PATCH http://localhost:3000/api/users/2
Content-Type: application/json

{
    "name": "test2",
    "lastName": "test2",
    "email": "teste2@test.com"
}

###

PATCH http://localhost:3000/api/users/1/active